### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mavaddat** [KnisterPeter/vscode-github#756] opened 2021-02-20 21:08 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension version: 0.30.4
- VS Code version: Code - Insiders 1.54.0-insider (a699ffaee62010c4634d301da2bbdb7646b8d1da, 2021-02-15T05:17:48.792Z)
- OS version: Windows_NT x64 10.0.21313

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz (4 x 2990)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.66GB free)|
|Process Argv|--crash-reporter-id 5fbb05cc-8424-46f5-a920-45fc0475991e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
core-portspanel:30257802
pythontb:30258533
wslfolderdoccf:30257852

```

</details>

[KnisterPeter.vscode-github-unresponsive.cpuprofile.txt](https://github.com/KnisterPeter/vscode-github/files/6016414/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt)

**Comment by KnisterPeter** [comment] 2021-02-22 07:51
Duplicate of #443

**Closed by KnisterPeter** 2021-02-22 07:51 UTC
