### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by marfino3028** [KnisterPeter/vscode-github#593] opened 2019-12-18 04:19 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.3`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Fino\KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment] 2019-12-19 08:46
Duplicate of #443

**Closed by KnisterPeter** 2019-12-19 08:46 UTC
