### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by UzuHero** [KnisterPeter/vscode-github#525] opened 2019-04-21 13:24 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.2`
- OS Version: `Linux x64 4.18.0-17-generic`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/uzuhero/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment] 2019-04-23 09:51
Duplicate of #443

**Closed by KnisterPeter** 2019-04-23 09:51 UTC
