### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by domtaylor** [KnisterPeter/vscode-github#727] opened 2020-12-13 10:22 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.4`
- OS Version: `Windows_NT x64 10.0.20262`
- VSCode version: `1.52.0`

[KnisterPeter.vscode-github-unresponsive.cpuprofile.txt](https://github.com/KnisterPeter/vscode-github/files/5684449/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt)
`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment] 2020-12-29 12:03
Duplicate of #443

**Closed by KnisterPeter** 2020-12-29 12:03 UTC
