### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vishalicodelabs** [KnisterPeter/vscode-github#765] opened 2021-03-02 04:41 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.4`
- OS Version: `Linux x64 5.8.0-44-generic`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment] 2021-03-02 07:59
Duplicate of #443

**Closed by KnisterPeter** 2021-03-02 07:59 UTC
