### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by matheus-santos-moreira** [KnisterPeter/vscode-github#633] opened 2020-04-14 11:44 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.3`
- OS Version: `Linux x64 5.0.0-32-generic`
- VSCode version: `1.43.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/matheus/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment] 2020-04-20 07:07
Duplicate of #443

**Closed by KnisterPeter** 2020-04-20 07:07 UTC
