### ISSUE TITLE
Improve UX when user try to create PR from unpublish branch

### ISSUE THREAD

**Issue by guillaumemolter** [KnisterPeter/vscode-github#78] opened 2017-03-21 13:14 UTC
Currently if you hit "Create PR" on an unpublished branch...
![screen shot 2017-03-20 at 14 57 35](https://cloud.githubusercontent.com/assets/1478527/24148503/7e4d43bc-0e15-11e7-8392-aef0723f001b.png)
...you get the following error message...
![screen shot 2017-03-20 at 14 57 22](https://cloud.githubusercontent.com/assets/1478527/24148506/87938116-0e15-11e7-91e2-200e785fed99.png)
...which is not very clear and can be really confusing for none power users.

Here are 4 ways this could be improved, I think the first option is the best but it is also clearly the one that requires the most work:
1. When clicking on create PR from an unpublished branch, user should receive a notification "Your branch needs to be published before you can create a PR [Publish and Create PR] [Cancel]"
2. The current error message should be replaced by something more verbose "You need to publish your branch before you can create a PR"
3. We could assume that it is obvious and simply publish automatically without prompt and then create the PR.
4. The Create PR button should be greyed out when the branch is not published.

**Comment by KnisterPeter** [comment] 2017-03-21 20:48
Duplicate of #61

**Closed by KnisterPeter** 2017-03-21 20:48 UTC

**Comment by KnisterPeter** [comment] 2017-03-21 20:49
Good ideas, I've referenced them so they are linked from the bug report
