### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kimbar** [KnisterPeter/vscode-github#761] opened 2021-02-24 16:57 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.4`
- OS Version: `Windows_NT ia32 6.1.7601`
- VSCode version: `1.53.2`

[KnisterPeter.vscode-github-unresponsive.cpuprofile.txt](https://github.com/KnisterPeter/vscode-github/files/6037583/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment] 2021-02-25 07:50
Duplicate of #443

**Closed by KnisterPeter** 2021-02-25 07:50 UTC
