### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mavaddat** [KnisterPeter/vscode-github#724] opened 2020-12-10 02:53 UTC
- Issue Type: `Bug`
- Extension Name: `vscode-github`
- Extension Version: `0.30.4`
- OS Version: `Windows_NT x64 10.0.20270`
- VSCode version: `1.52.0-insider`

[KnisterPeter.vscode-github-unresponsive.cpuprofile.txt](https://github.com/KnisterPeter/vscode-github/files/5669987/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt)
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 17016,
		"activateCallTime": 164,
		"activateResolvedTime": 125,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "KnisterPeter.vscode-github",
				"_lower": "knisterpeter.vscode-github"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by KnisterPeter** [comment] 2020-12-29 12:03
Duplicate of #443

**Closed by KnisterPeter** 2020-12-29 12:03 UTC
