### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by DivyanshArya-23** [KnisterPeter/vscode-github#697] opened 2020-09-21 07:07 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.3`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.49.0`

[KnisterPeter.vscode-github-unresponsive.cpuprofile.txt](https://github.com/KnisterPeter/vscode-github/files/5253866/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment] 2020-10-02 15:54
Duplicate of #443

**Closed by KnisterPeter** 2020-10-02 15:54 UTC
