### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by andredev-jpg** [KnisterPeter/vscode-github#714] opened 2020-11-13 16:38 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.4`
- OS Version: `Windows_NT ia32 6.1.7601`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\IGOR\AppData\Local\Temp\KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment] 2020-11-19 07:57
Duplicate of #443

**Closed by KnisterPeter** 2020-11-19 07:57 UTC
