### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kamshory** [KnisterPeter/vscode-github#778] opened 2021-03-27 13:40 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.5`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.55.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\kamshory\AppData\Local\Temp\KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment] 2021-03-27 16:41
Duplicate of #443

**Closed by KnisterPeter** 2021-03-27 16:41 UTC
