### ISSUE TITLE
`git log` failure when trying to create a PR

### ISSUE THREAD

**Issue by viraptor** [KnisterPeter/vscode-github#138] opened 2017-07-18 02:00 UTC
I'm trying to create a PR. I get the following issue after selecting the remote and target branch:
```
Command failed: git log --format=%b -n 1 
fatal: ambiguous argument ''
```
This happens on version 0.17.1

**Comment by KnisterPeter** [comment] 2017-07-19 06:49
Duplicate of #114

**Closed by KnisterPeter** 2017-07-19 06:49 UTC
