### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Rajpratik71** [KnisterPeter/vscode-github#507] opened 2019-03-21 17:17 UTC
[KnisterPeter.vscode-github-unresponsive.cpuprofile.txt](https://github.com/KnisterPeter/vscode-github/files/2993196/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.1`
- OS Version: `Linux x64 4.15.0-24-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/reddragon/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment] 2019-03-25 10:15
Duplicate of #443

**Closed by KnisterPeter** 2019-03-25 10:15 UTC
