### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jmsfrancies** [KnisterPeter/vscode-github#592] opened 2019-12-14 16:25 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.3`
- OS Version: `Darwin x64 19.2.0`
- VSCode version: `1.41.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/jamesboonfrancies/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment] 2019-12-17 09:09
Duplicate of #443

**Closed by KnisterPeter** 2019-12-17 09:09 UTC
