### ISSUE TITLE
"Cannot read property slice of null" when trying to set an access token

### ISSUE THREAD

**Issue by lunaryorn** [KnisterPeter/vscode-github#107] opened 2017-05-19 07:41 UTC
When I try to set the access token I get the above error.  The Developer Tools console has the following to say on this error:

<details>
<summary>Developer Tools Console log</summary>
<p>

~~~
shell.ts:474 Cannot read property 'slice' of null: TypeError: Cannot read property 'slice' of null
    at /Users/sebastian.wiesner/.vscode/extensions/KnisterPeter.vscode-github-0.15.1/out/src/git.js:50:39
    at Generator.next (<anonymous>)
    at fulfilled (/Users/sebastian.wiesner/.vscode/extensions/KnisterPeter.vscode-github-0.15.1/out/src/git.js:4:58)
e.onUnexpectedError @ shell.ts:474
(anonymous) @ shell.ts:434
e.onUnexpectedError @ errors.ts:68
o @ errors.ts:88
(anonymous) @ winjs.base.js:43
(anonymous) @ winjs.base.js:38
winjs.base.js:45 WARNING: Promise with no error callback:92
winjs.base.js:46 Objecterror: Error: Cannot read property 'slice' of null
    at /Users/sebastian.wiesner/.vscode/extensions/KnisterPeter.vscode-github-0.15.1/out/src/git.js:50:39
    at Generator.next (<anonymous>)
    at fulfilled (/Users/sebastian.wiesner/.vscode/extensions/KnisterPeter.vscode-github-0.15.1/out/src/git.js:4:58)message: "Cannot read property 'slice' of null"name: "TypeError"stack: "TypeError: Cannot read property 'slice' of null↵    at /Users/sebastian.wiesner/.vscode/extensions/KnisterPeter.vscode-github-0.15.1/out/src/git.js:50:39↵    at Generator.next (<anonymous>)↵    at fulfilled (/Users/sebastian.wiesner/.vscode/extensions/KnisterPeter.vscode-github-0.15.1/out/src/git.js:4:58)"__proto__: Objectexception: nullhandler: undefinedid: 92parent: undefinedpromise: n.Class.derive._oncancel__proto__: Object
messageService.ts:125 Cannot read property 'slice' of null
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
e.resume @ messageService.ts:63
(anonymous) @ workbench.ts:856
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ quickOpenController.ts:513
~~~

</p>
</details>

----

I'm not sure how to debug this issue further, and would appreciate any hints :)  If you need further information please tell me.

**Comment by KnisterPeter** [comment] 2017-05-22 08:24
@lunaryorn the token is already set and the problem is then in the git access. Can you tell me the git url you checked out your project with? Like `git@github:username/repo.git`.  
The parsing of this url to extract username and repo fails.

**Comment by lunaryorn** [comment] 2017-05-22 08:35
@KnisterPeter Where can I see the token?  I didn't find anything in `settings.json`…

The URL is `github.com:lunaryorn/xkpwgen.hs.git`, but it fails with `git@github.com:lunaryorn/xkpwgen.hs.git` too.

**Comment by KnisterPeter** [comment] 2017-05-22 09:46
The token is stored in the global settings of vscode since it should work for more than the current workspace.

The bug will be fixed in the next release I publish later today. Thanks for reporting.

**Closed** 2017-05-22 09:54 UTC
Labels: bug, question

**Comment by KnisterPeter** [comment] 2017-05-22 09:58
Released in 0.16

**Comment by lunaryorn** [comment] 2017-05-22 10:14
@KnisterPeter Thanks a lot, works now ❤️ 👍

**Comment by lunaryorn** [comment] 2017-05-22 10:18
PS: I noticed that the `git@` part is mandatory for a remote to be recognised as Github remote.

Could you perhaps make it optional?  I [set the username in my SSH configuration](https://github.com/lunaryorn/dotfiles/blob/eb91dbe830fa2b3fc95b0368f9540bdd50d9cd9a/ssh/.ssh/config#L8).  There's no other user name you could use with Github's SSH server, so it's convenient to have it set as default.

**Comment by KnisterPeter** [comment] 2017-05-22 10:23
Would be possible if restricted to github.com as hostname.
Could you please file a new issue for that?

**Comment by lunaryorn** [comment] 2017-05-22 10:25
Ah, I didn't think of Github Enterprise. 

I'll open a new issue.

**Comment by lunaryorn** [comment] 2017-05-22 10:26
I opened #110
