### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ericksosagarcia** [KnisterPeter/vscode-github#606] opened 2020-01-13 23:48 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.3`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\queba\KnisterPeter.vscode-github-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mavaddat** [comment] 2020-01-20 00:07
[KnisterPeter.vscode-github-unresponsive.cpuprofile.txt](https://github.com/KnisterPeter/vscode-github/files/4083949/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt)


> * Issue Type: `Performance`
> * Extension Name: `vscode-github`
> * Extension Version: `0.30.3`  (2019-10-27)
> * OS Version: `Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0`
> * VSCode details: `Version: 1.42.0-insider (user setup)
Commit: fd13e449f5f2fe300f187129d6065ed1cfad74d3
Date: 2020-01-17T17:23:31.960Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363`

**Comment by KnisterPeter** [comment] 2020-02-03 08:41
Duplicate of #443

**Closed by KnisterPeter** 2020-02-03 08:41 UTC
