### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yuki-yoshizawa** [KnisterPeter/vscode-github#481] opened 2019-02-07 08:27 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-github`
- Extension Version: `0.30.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/yukiyoshizawa/KnisterPeter.vscode-github-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by KnisterPeter** [comment] 2019-02-11 08:09
Duplicate of #443

**Closed by KnisterPeter** 2019-02-11 08:09 UTC
